### ISSUE TITLE
Fix usage of (or workaround for bug in) tumult Simplex2

### ISSUE THREAD

**Issue by martinblech** [PampaWarro/warrolight#41]
If I leave the noise program running for a while, I  get this stacktrace:
```
/Users/martinblech/Documents/projects/warrolight/server/node_modules/tumult/lib/simplex/simplex2.js:30
    const n2 = cut(dx2, dy2) * grad2(this.p, i + 1, j + 1).dot(dx2, dy2)
                                                          ^
TypeError: Cannot read property 'dot' of undefined
    at Simplex2.gen (/Users/martinblech/Documents/projects/warrolight/server/node_modules/tumult/lib/simplex/simplex2.js:30:59)
    at Noise.drawFrame (/Users/martinblech/Documents/projects/warrolight/server/src/light-programs/programs/noise.js:46:17)
    at Timeout.frame [as _onTimeout] (/Users/martinblech/Documents/projects/warrolight/server/src/ProgramScheduler.js:30:20)
```

Not sure if there's something wrong with our program or this is exposing some bug in tumult. @federicobond can you please take a look?

**Comment by federicobond** [comment]
Oh, yes, apparently when the noise function is called with too high a parameter it crashes, we can fix it with a wraparound beyond a certain point. I will do that and also try to make the color differences more marked.
